# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pass_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Pass_Widget(object):
    def setupUi(self, Pass_Widget):
        Pass_Widget.setObjectName("Pass_Widget")
        Pass_Widget.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Pass_Widget)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_OK = QtWidgets.QPushButton(Pass_Widget)
        self.pushButton_OK.setObjectName("pushButton_OK")
        self.gridLayout.addWidget(self.pushButton_OK, 4, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 2)
        self.lineEdit_password_2 = QtWidgets.QLineEdit(Pass_Widget)
        self.lineEdit_password_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password_2.setObjectName("lineEdit_password_2")
        self.gridLayout.addWidget(self.lineEdit_password_2, 2, 1, 1, 2)
        self.lineEdit_password_1 = QtWidgets.QLineEdit(Pass_Widget)
        self.lineEdit_password_1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password_1.setObjectName("lineEdit_password_1")
        self.gridLayout.addWidget(self.lineEdit_password_1, 1, 1, 1, 2)
        self.label = QtWidgets.QLabel(Pass_Widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(Pass_Widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 5, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Pass_Widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_no_match = QtWidgets.QLabel(Pass_Widget)
        self.label_no_match.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_no_match.setObjectName("label_no_match")
        self.gridLayout.addWidget(self.label_no_match, 3, 0, 1, 3)

        self.retranslateUi(Pass_Widget)
        QtCore.QMetaObject.connectSlotsByName(Pass_Widget)

    def retranslateUi(self, Pass_Widget):
        _translate = QtCore.QCoreApplication.translate
        Pass_Widget.setWindowTitle(_translate("Pass_Widget", "Form"))
        self.pushButton_OK.setText(_translate("Pass_Widget", "OK"))
        self.label.setText(_translate("Pass_Widget", "Set password for the Ubuntu-user \"epics\":"))
        self.label_2.setText(_translate("Pass_Widget", "Password:"))
        self.label_3.setText(_translate("Pass_Widget", "Repeat Password:"))
        self.label_no_match.setText(_translate("Pass_Widget", "Passwords don\'t match!"))
